# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "google_pagerank"
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sebastian Johnsson"]
  s.date = "2012-01-26"
  s.description = "API for fetching Google Pagerank"
  s.email = "sebastian@agiley.se"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "google_pagerank.gemspec",
    "lib/google/pagerank/client.rb",
    "lib/google_pagerank.rb",
    "lib/tasks/google_pagerank_tasks.rake",
    "spec/google_pagerank/client_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/Agiley/google_pagerank"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "API for fetching Google Pagerank"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_runtime_dependency(%q<http_utilities>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<mysql2>, ["= 0.2.7"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<http_utilities>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<mysql2>, ["= 0.2.7"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<http_utilities>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<mysql2>, ["= 0.2.7"])
  end
end

